GET https://api.redgifs.com/v2/auth/temporary
###
GET https://api.redgifs.com/v2/gifs/search?search_text=strap_on&count=5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3NTY5MzM5NzIsImF1ZCI6Imh0dHBzOi8vYXBpLnJlZGdpZnMuY29tIiwiYXpwIjoiMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwiZXhwIjoxNzU3MDIwMzcyLCJzdWIiOiJjbGllbnQvMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwic2NvcGVzIjoicmVhZCIsInZhbGlkX2FkZHIiOiI4Mi40NS4zMi4xNzYiLCJ2YWxpZF9hZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwicmF0ZSI6LTEsImh0dHBzOi8vcmVkZ2lmcy5jb20vc2Vzc2lvbi1pZCI6IjMxOTgyODUxODEwNjE3NTg5MiJ9.Bw7wYIXDjp8StfSoWckUwJzF6kjgd1U42dSLaHhuQ9zyNVZU-56hW3PgzneMwaKotIcV7jv8UU1np1WkzwTQcNwi61St9oOfHRpUdzLWgb1fCA0pw9QRRmHE-bGIX_M5bcgP1B95I27qpmXVUA4Drl1K989zhxWwOs0KaNd1SBJV4CB3oj7qSJAl-kVJ_PY0y1MviX0Rn_S3k3chvsvwqoFdaqKikQKdgzmcv2RpglCXoqf2GR_gE7mbM3XTkke1Y5Pd5c3UOh9ggabGZ_9xsx_cMamQRTdtZoR70nDakhn8RRD5QapcXgiYK-5UFe-E38z0W_et6otIiNzIypkw1w


###
GET https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324&json=1&tags=big_tits+animated+futanari+standing_dp

###
GET https://api.rule34.xxx/index.php?page=dapi&s=tag&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324