name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.5.0
        name: Login to Docker Registry
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: "https://docker.kannonfoundry.dev"
          # Username used to log against the Docker registry
          username: kannonfodder
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker buildx build --platform "linux/arm64,linux/amd64" --tag docker.kannonfoundry.dev/whutbot3 --push .
