name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner || 'ubuntu-22.04' }}

    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Starting build of whutbot"
          username: GitHub Actions
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: docker/login-action@v3.5.0
        name: Login to Docker Registry
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: "https://docker.kannonfoundry.dev"
          # Username used to log against the Docker registry
          username: kannonfodder
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=docker.kannonfoundry.dev/whutbot3,push-by-digest=true,name-canonical=true,push=${{github.ref == 'res/heads/main' ? "true":"false"}}
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push docker.kannonfoundry.dev/whutbot3
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Finished build of whutbot"
          status: ${{ job.status }}
          username: GitHub Actions
