name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: docker/login-action@v3.5.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: "https://docker.kannonfoundry.dev"
        # Username used to log against the Docker registry
        username: # optional
        # Password or personal access token used to log against the Docker registry
        password: # optional
